"""org todo graph: วง · การแชร์ · dependency (ADR 0049)

สี่ตารางใหม่ ตารางเปล่าทั้งหมด — ไม่มีข้อมูลเดิมให้ย้าย จึงไม่ต้องสำรอง/เขียนกลับ
ทุกคอลัมน์เวลาใช้ `UTCDateTime` ตามวินัย dialect

Revision ID: 035904aa4770
Revises: a7c41d90b3ef
Create Date: 2026-08-15 03:42:50.687246

"""
from alembic import op

from app.db_types import UTCDateTime
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '035904aa4770'
down_revision = 'a7c41d90b3ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tdl_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', UTCDateTime, nullable=True),
    sa.Column('deleted_at', UTCDateTime, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tdl_team')),
    sa.UniqueConstraint('name', name=op.f('uq_tdl_team_name'))
    )
    with op.batch_alter_table('tdl_team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tdl_team_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('tdl_team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', UTCDateTime, nullable=True),
    sa.Column('deleted_at', UTCDateTime, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['tdl_team.id'], name=op.f('fk_tdl_team_member_team_id_tdl_team'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tdl_user.id'], name=op.f('fk_tdl_team_member_user_id_tdl_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tdl_team_member')),
    sa.UniqueConstraint('team_id', 'user_id', name=op.f('uq_tdl_team_member_team_id'))
    )
    with op.batch_alter_table('tdl_team_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tdl_team_member_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tdl_team_member_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tdl_team_member_user_id'), ['user_id'], unique=False)

    op.create_table('tdl_todo_dependency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_todo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', UTCDateTime, nullable=True),
    sa.Column('accepted_at', UTCDateTime, nullable=True),
    sa.Column('deleted_at', UTCDateTime, nullable=True),
    sa.ForeignKeyConstraint(['depends_on_todo_id'], ['tdl_todo.id'], name=op.f('fk_tdl_todo_dependency_depends_on_todo_id_tdl_todo'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['todo_id'], ['tdl_todo.id'], name=op.f('fk_tdl_todo_dependency_todo_id_tdl_todo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tdl_todo_dependency')),
    sa.UniqueConstraint('todo_id', 'depends_on_todo_id', name=op.f('uq_tdl_todo_dependency_todo_id'))
    )
    with op.batch_alter_table('tdl_todo_dependency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tdl_todo_dependency_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tdl_todo_dependency_depends_on_todo_id'), ['depends_on_todo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tdl_todo_dependency_todo_id'), ['todo_id'], unique=False)

    op.create_table('tdl_todo_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('shared_at', UTCDateTime, nullable=True),
    sa.Column('deleted_at', UTCDateTime, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['tdl_team.id'], name=op.f('fk_tdl_todo_share_team_id_tdl_team'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['todo_id'], ['tdl_todo.id'], name=op.f('fk_tdl_todo_share_todo_id_tdl_todo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tdl_todo_share')),
    sa.UniqueConstraint('todo_id', 'team_id', name=op.f('uq_tdl_todo_share_todo_id'))
    )
    with op.batch_alter_table('tdl_todo_share', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tdl_todo_share_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tdl_todo_share_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tdl_todo_share_todo_id'), ['todo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tdl_todo_share', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tdl_todo_share_todo_id'))
        batch_op.drop_index(batch_op.f('ix_tdl_todo_share_team_id'))
        batch_op.drop_index(batch_op.f('ix_tdl_todo_share_deleted_at'))

    op.drop_table('tdl_todo_share')
    with op.batch_alter_table('tdl_todo_dependency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tdl_todo_dependency_todo_id'))
        batch_op.drop_index(batch_op.f('ix_tdl_todo_dependency_depends_on_todo_id'))
        batch_op.drop_index(batch_op.f('ix_tdl_todo_dependency_deleted_at'))

    op.drop_table('tdl_todo_dependency')
    with op.batch_alter_table('tdl_team_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tdl_team_member_user_id'))
        batch_op.drop_index(batch_op.f('ix_tdl_team_member_team_id'))
        batch_op.drop_index(batch_op.f('ix_tdl_team_member_deleted_at'))

    op.drop_table('tdl_team_member')
    with op.batch_alter_table('tdl_team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tdl_team_deleted_at'))

    op.drop_table('tdl_team')
    # ### end Alembic commands ###
