"""baseline: schema ของ core ทั้งชุด — ยุบสาย 13 ตัวของ Phase 1–4 (Phase 5)

Revision ID: 5ffefa218ed7
Revises:
Create Date: 2026-08-07

**ทำไมต้องยุบ:** สายเดิมมี raw SQL สามจุดที่อ้างตาราง `user` โดยไม่ quote
(migration `296ab616c11b` ตอนแยก theme ออกเป็น theme+mode) ซึ่งเป็น reserved word
ของ PostgreSQL/Oracle/MSSQL — fresh install บนยี่ห้อพวกนั้นจะพังตั้งแต่ migration
ตัวที่เจ็ด ทั้งที่ตารางชื่อนั้นไม่มีอยู่ในระบบแล้วตั้งแต่ใส่ prefix `tdl_`
(ROADMAP ข้อ 4.4 ตั้งไว้ว่าจะล้างด้วยการ squash ตอน Phase 5 — นี่คือขั้นนั้น)

**ฐานข้อมูลที่มีอยู่แล้วไม่ต้องทำอะไร** — `env.py` รับช่วงเวอร์ชันให้เอง
(ดู `_adopt_squashed_history()`) หลักเดียวกับตอนเปลี่ยนชื่อ `alembic_version`
เป็น `tdl_alembic_version` คือทำให้อัตโนมัติ ไม่ใช่สั่งให้คนไปพิมพ์ `db stamp` เอง

**สิ่งที่ไฟล์นี้สร้าง เท่ากับสิ่งที่สายเดิมสร้างทุกประการ** ยกเว้นลำดับคอลัมน์
ของ `tdl_user` ซึ่งสายเดิมได้ `deleted_at, purged_at, role` จากการ ALTER ทีละรอบ
ส่วนที่นี่ได้ตามลำดับที่ประกาศใน model — ตรวจแล้วว่าไม่มีอะไรในระบบพึ่งลำดับ
คอลัมน์ (`audit._canonical()` เรียงคีย์เอง, ไม่มี `SELECT *` และไม่มีการอ่านผล
แบบตำแหน่งที่ไหนเลย) ฐานเดิมจึงเก็บลำดับเดิมไว้ได้โดยไม่ต้องเรียงใหม่

**ตารางของ plugin ไม่อยู่ในนี้** ตาม ADR 0023 — เกิดจาก `flask plugin-install`
"""
from alembic import op
import sqlalchemy as sa

from app.db_types import UTCDateTime


# revision identifiers, used by Alembic.
revision = '5ffefa218ed7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tdl_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime, nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('table_name', sa.String(length=64), nullable=True),
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('changes', sa.Text(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tdl_audit')),
    sa.UniqueConstraint('prev_hash', name='uq_audit_prev_hash'),
    sa.UniqueConstraint('row_hash', name='uq_audit_row_hash')
    )
    op.create_index(op.f('ix_tdl_audit_actor_id'), 'tdl_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_tdl_audit_created_at'), 'tdl_audit', ['created_at'], unique=False)
    op.create_index(op.f('ix_tdl_audit_event'), 'tdl_audit', ['event'], unique=False)
    op.create_table('tdl_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', UTCDateTime, nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=True),
    sa.Column('theme', sa.String(length=32), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=True),
    sa.Column('timezone_name', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('role', sa.String(length=16), server_default='user', nullable=False),
    sa.Column('purged_at', UTCDateTime, nullable=True),
    sa.Column('deleted_at', UTCDateTime, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tdl_user')),
    sa.UniqueConstraint('username', name=op.f('uq_tdl_user_username'))
    )
    op.create_index(op.f('ix_tdl_user_deleted_at'), 'tdl_user', ['deleted_at'], unique=False)
    op.create_table('tdl_api_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', UTCDateTime, nullable=True),
    sa.Column('expires_at', UTCDateTime, nullable=True),
    sa.Column('deleted_at', UTCDateTime, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tdl_user.id'], name=op.f('fk_tdl_api_token_user_id_tdl_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tdl_api_token'))
    )
    op.create_index(op.f('ix_tdl_api_token_deleted_at'), 'tdl_api_token', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tdl_api_token_user_id'), 'tdl_api_token', ['user_id'], unique=False)
    op.create_table('tdl_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', UTCDateTime, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tdl_user.id'], name=op.f('fk_tdl_category_user_id_tdl_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tdl_category')),
    sa.UniqueConstraint('user_id', 'name', name='uq_category_user_name')
    )
    op.create_index(op.f('ix_tdl_category_deleted_at'), 'tdl_category', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tdl_category_user_id'), 'tdl_category', ['user_id'], unique=False)
    op.create_table('tdl_todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime, nullable=True),
    sa.Column('updated_at', UTCDateTime, nullable=True),
    sa.Column('start_date', UTCDateTime, nullable=True),
    sa.Column('due_date', UTCDateTime, nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', UTCDateTime, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tdl_category.id'], name=op.f('fk_tdl_todo_category_id_tdl_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['tdl_user.id'], name=op.f('fk_tdl_todo_user_id_tdl_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tdl_todo'))
    )
    op.create_index(op.f('ix_tdl_todo_deleted_at'), 'tdl_todo', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tdl_todo_user_id'), 'tdl_todo', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tdl_todo_user_id'), table_name='tdl_todo')
    op.drop_index(op.f('ix_tdl_todo_deleted_at'), table_name='tdl_todo')
    op.drop_table('tdl_todo')
    op.drop_index(op.f('ix_tdl_category_user_id'), table_name='tdl_category')
    op.drop_index(op.f('ix_tdl_category_deleted_at'), table_name='tdl_category')
    op.drop_table('tdl_category')
    op.drop_index(op.f('ix_tdl_api_token_user_id'), table_name='tdl_api_token')
    op.drop_index(op.f('ix_tdl_api_token_deleted_at'), table_name='tdl_api_token')
    op.drop_table('tdl_api_token')
    op.drop_index(op.f('ix_tdl_user_deleted_at'), table_name='tdl_user')
    op.drop_table('tdl_user')
    op.drop_index(op.f('ix_tdl_audit_event'), table_name='tdl_audit')
    op.drop_index(op.f('ix_tdl_audit_created_at'), table_name='tdl_audit')
    op.drop_index(op.f('ix_tdl_audit_actor_id'), table_name='tdl_audit')
    op.drop_table('tdl_audit')
    # ### end Alembic commands ###
