"""add theme to user

Revision ID: 81b7c3f4e01f
Revises: 8caa5996801f
Create Date: 2026-08-02 17:24:12.069044

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "81b7c3f4e01f"
down_revision = "8caa5996801f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("theme", sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("theme")

    # ### end Alembic commands ###
