"""บันทึกการเปลี่ยนชื่อวง (CR#3) — ตารางเปล่า ไม่มีข้อมูลเดิมให้ย้าย

Revision ID: d2d3bba3fb39
Revises: 035904aa4770
Create Date: 2026-08-15 17:10:36.983186

"""
from alembic import op

from app.db_types import UTCDateTime
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd2d3bba3fb39'
down_revision = '035904aa4770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tdl_team_name_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', UTCDateTime, nullable=True),
    sa.Column('old_name', sa.String(length=80), nullable=False),
    sa.Column('new_name', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('deleted_at', UTCDateTime, nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['tdl_user.id'], name=op.f('fk_tdl_team_name_change_changed_by_id_tdl_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['tdl_team.id'], name=op.f('fk_tdl_team_name_change_team_id_tdl_team'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tdl_team_name_change'))
    )
    with op.batch_alter_table('tdl_team_name_change', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tdl_team_name_change_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tdl_team_name_change_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tdl_team_name_change', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tdl_team_name_change_team_id'))
        batch_op.drop_index(batch_op.f('ix_tdl_team_name_change_deleted_at'))

    op.drop_table('tdl_team_name_change')
    # ### end Alembic commands ###
